# Generated by Django 5.1.10 on 2026-01-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_of_leaving',
            new_name='date_of_exit',
        ),
    ]
