# Generated by Django 5.1.10 on 2026-03-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_seen_ai_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_seen_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
