# Generated by Django 5.1.10 on 2026-05-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_has_seen_ai_onboarding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='razorpay_contact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='razorpay_fund_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
