# Generated by Django 5.1.10 on 2026-05-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userloginhistory_latitude_userloginhistory_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginhistory',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True),
        ),
    ]
