# Generated by Django 5.1.10 on 2026-06-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userloginhistory_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
