# Generated by Django 5.1.10 on 2026-08-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_email_login_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='face_descriptor',
            field=models.JSONField(blank=True, help_text='Normalized face descriptor vector produced by the client face pipeline', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='face_enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='face_enrollment_image',
            field=models.ImageField(blank=True, null=True, upload_to='teamzen/face_enrollment/'),
        ),
    ]
