# Generated by Django 5.1.10 on 2026-08-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_face_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='face_enrollment_image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='teamzen/face_enrollment/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='teamzen/user_profile/'),
        ),
    ]
