# Generated by Django 5.1.10 on 2026-08-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_clear_legacy_face_descriptors'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='residential_address',
            field=models.TextField(blank=True, default='', help_text='Residential / permanent address for Form 16 and letters'),
        ),
    ]
