# Generated by Django 5.1.10 on 2026-09-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_form16_tax_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='residential_address',
            field=models.TextField(blank=True, default='', help_text='Residential / permanent address'),
        ),
    ]
