# Generated by Django 5.1.10 on 2026-02-16 12:59

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_initial'),
        ('organizations', '0005_alter_department_id_alter_designation_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policydocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='PolicyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='policy_pdfs')),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_files', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy File',
                'verbose_name_plural': 'Policy Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='policydocument',
            name='policy_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='ai_engine.policyfile'),
        ),
        migrations.AddIndex(
            model_name='policydocument',
            index=models.Index(fields=['-created_at'], name='ai_engine_p_created_bd9e48_idx'),
        ),
    ]
