# Generated by Django 5.1.10 on 2026-03-22 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_alter_policydocument_options_policyfile_and_more'),
        ('organizations', '0006_organization_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('gpt-4o', 'GPT-4o (OpenAI Premium)'), ('gpt-4o-mini', 'GPT-4o Mini (OpenAI Fast)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Google Free/Fast)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (Google Premium)'), ('llama-3-8b-8192', 'Llama 3 8B (Groq Free/Fast)'), ('llama-3-70b-8192', 'Llama 3 70B (Groq Smart)'), ('mixtral-8x7b-32768', 'Mixtral 8x7B (Groq Fast)')], default='gpt-4o', max_length=50)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=1024)),
                ('system_prompt_override', models.TextField(blank=True, help_text='Custom instructions for the AI', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='organizations.organization')),
            ],
        ),
    ]
