# Generated by Django 5.1.10 on 2026-03-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_aiconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='model_name',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o (OpenAI Premium)'), ('gpt-4o-mini', 'GPT-4o Mini (OpenAI Fast)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Google Free/Fast)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (Google Premium)'), ('llama-3.3-70b-versatile', 'Llama 3.3 70B (Groq Smart)'), ('llama-3.1-8b-instant', 'Llama 3.1 8B (Groq Free/Fast)'), ('mixtral-8x7b-32768', 'Mixtral 8x7B (Groq Fast)')], default='gpt-4o', max_length=50),
        ),
    ]
