# Generated by Django 5.1.10 on 2026-07-29 15:56

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0005_alter_aiconfiguration_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydocument',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='policydocument',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='ai_engine_p_search__19e537_gin'),
        ),
    ]
