from celery import shared_task
from django.utils import timezone
from datetime import date, time


@shared_task(name="attendance.tasks.square_off_incomplete_checkouts")
def square_off_incomplete_checkouts():
    """
    Runs at midnight (Asia/Kolkata) every day.

    Finds all AttendanceRecords for TODAY where:
      - login_time is set (user checked in)
      - logout_time is null (user forgot to check out)
      - No AttendanceCorrection already exists for the record

    For each such record:
      1. Sets logout_time to 23:59 (end of day) and recalculates worked_hours
      2. Updates status to 'present' (partial day worked)
      3. Creates an AttendanceCorrection in 'pending' state so the
         HR/manager sees it as needing review, and the user's Last 7 Days
         dot shows 'pending' on the dashboard.
      4. Sends the employee an in-app notification.
    """
    from attendance.models import AttendanceRecord, AttendanceCorrection
    from notifications.tasks import send_notification

    today = date.today()
    eod = time(23, 59, 0)  # treat end-of-day as 23:59

    # Find incomplete check-ins for today
    incomplete = AttendanceRecord.objects.filter(
        attendance_date=today,
        login_time__isnull=False,
        logout_time__isnull=True,
    ).select_related('user')

    count = 0
    for record in incomplete:
        # Skip if a correction request already exists (avoid duplicates)
        already_corrected = AttendanceCorrection.objects.filter(
            attendance_record=record
        ).exists()
        if already_corrected:
            continue

        # 1. Auto square-off: set logout to 23:59 so worked_hours aren't null
        record.logout_time = eod
        record.recalculate_worked_hours()
        record.remarks = (
            f"{record.remarks}\n[Auto square-off at 23:59 — checkout not recorded.]"
        ).strip()
        record.save(update_fields=['logout_time', 'worked_hours', 'remarks'])

        # 2. Create a pending AttendanceCorrection so the record shows as
        #    "pending correction" on the dashboard's Last 7 Days widget.
        AttendanceCorrection.objects.create(
            attendance_record=record,
            requested_by=record.user,
            corrected_logout_time=None,   # Employee/HR fills in the real time
            reason="Missed checkout – auto-generated by system at end of day. "
                   "Please submit your actual logout time.",
        )

        # 3. Notify the employee
        send_notification.delay(
            recipient_id=record.user.id,
            verb="Missed Checkout Detected",
            message=(
                f"You forgot to check out on {today.strftime('%b %d, %Y')}. "
                "Your attendance has been auto-squared off at 23:59. "
                "Please submit an attendance correction with your actual logout time."
            ),
            notification_type='PUSH',
            target_type='Attendance',
            target_id=str(record.id),
            level='warning',
        )

        count += 1

    return f"Auto square-off complete: {count} record(s) processed for {today}."
