from celery import shared_task
from django.utils import timezone
from datetime import date, time, datetime, timedelta
from statistics import median


def _suggested_logout_time(user) -> time:
    """Median logout over last 14 checkouts, else 18:00."""
    from attendance.models import AttendanceRecord

    start = date.today() - timedelta(days=14)
    logouts = list(
        AttendanceRecord.objects.filter(
            user=user,
            attendance_date__gte=start,
            logout_time__isnull=False,
        )
        .exclude(remarks__icontains="Auto square-off")
        .values_list("logout_time", flat=True)[:30]
    )
    if not logouts:
        return time(18, 0, 0)

    # Convert times to minutes since midnight for median
    minutes = [t.hour * 60 + t.minute for t in logouts]
    mid = int(median(minutes))
    return time(mid // 60, mid % 60, 0)


@shared_task(name="attendance.tasks.square_off_incomplete_checkouts")
def square_off_incomplete_checkouts():
    """
    Runs at midnight (Asia/Kolkata) every day.

    Finds all AttendanceRecords for TODAY where:
      - login_time is set (user checked in)
      - logout_time is null (user forgot to check out)
      - No AttendanceCorrection already exists for the record

    For each such record:
      1. Sets logout_time to 23:59 (end of day) and recalculates worked_hours
      2. Creates an AttendanceCorrection in 'pending' state with a suggested
         corrected_logout_time (median of recent logouts or 18:00)
      3. Sends the employee an in-app notification.
    """
    from attendance.models import AttendanceRecord, AttendanceCorrection
    from notifications.tasks import send_notification

    today = date.today()
    eod = time(23, 59, 0)  # treat end-of-day as 23:59

    # Find incomplete check-ins for today
    incomplete = AttendanceRecord.objects.filter(
        attendance_date=today,
        login_time__isnull=False,
        logout_time__isnull=True,
    ).select_related('user')

    count = 0
    for record in incomplete:
        # Skip if a correction request already exists (avoid duplicates)
        already_corrected = AttendanceCorrection.objects.filter(
            attendance_record=record
        ).exists()
        if already_corrected:
            continue

        suggested = _suggested_logout_time(record.user)

        # 1. Auto square-off: set logout to 23:59 so worked_hours aren't null
        record.logout_time = eod
        record.recalculate_worked_hours()
        record.remarks = (
            f"{record.remarks}\n[Auto square-off at 23:59 — checkout not recorded.]"
        ).strip()
        record.save(update_fields=['logout_time', 'worked_hours', 'remarks'])

        # 2. Create a pending AttendanceCorrection with AI/system suggested logout
        AttendanceCorrection.objects.create(
            attendance_record=record,
            requested_by=record.user,
            corrected_logout_time=suggested,
            reason=(
                "Missed checkout – auto-generated by system at end of day. "
                f"Suggested logout {suggested.strftime('%H:%M')} "
                "(from your recent pattern or office default). "
                "Confirm via AI assistant or edit the time."
            ),
        )

        # 3. Notify the employee
        send_notification.delay(
            recipient_id=record.user.id,
            verb="Missed Checkout Detected",
            message=(
                f"You forgot to check out on {today.strftime('%b %d, %Y')}. "
                f"Suggested logout {suggested.strftime('%H:%M')}. "
                "Ask the AI assistant to confirm your correction in one tap."
            ),
            notification_type='PUSH',
            target_type='Attendance',
            target_id=str(record.id),
            level='warning',
        )

        count += 1

    return f"Auto square-off complete: {count} record(s) processed for {today}."
