# Generated by Django 5.1.10 on 2026-09-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_escalation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feedback',
            new_name='feedback_fe_escalat_863ad5_idx',
            old_name='feedback_fe_escalat_7c1a2b_idx',
        ),
    ]
