# Generated by Django 5.1.10 on 2026-01-06 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='login_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='logout_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
    ]
