# Generated by Django 5.1.10 on 2026-01-19 17:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_officelocation_login_time_officelocation_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\s\\-]+$', message='Zip codes may include letters, numbers, spaces, and hyphens.')]),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='geo_radius_meters',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='logout_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddIndex(
            model_name='officelocation',
            index=models.Index(fields=['city'], name='organizatio_city_d582e7_idx'),
        ),
        migrations.AddIndex(
            model_name='officelocation',
            index=models.Index(fields=['state'], name='organizatio_state_443008_idx'),
        ),
        migrations.AddIndex(
            model_name='officelocation',
            index=models.Index(fields=['country'], name='organizatio_country_5cd049_idx'),
        ),
    ]
