# Generated by Django 5.1.10 on 2026-01-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_officelocation_city_officelocation_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='teamzen/organization/'),
        ),
    ]
