# Generated by Django 5.1.10 on 2026-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='llm_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
