# Generated by Django 5.1.10 on 2026-07-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organization_accent'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payroll_auto_enabled',
            field=models.BooleanField(default=False, help_text='When True and plan is pro/elite, Celery auto-runs payroll on cycle day'),
        ),
        migrations.AddField(
            model_name='organization',
            name='payroll_cycle_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day of month (1–28) to auto-create previous month payroll'),
        ),
    ]
