# Generated by Django 5.1.10 on 2026-08-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_mcpdevicecode_mcpauthcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='face_attendance_enabled',
            field=models.BooleanField(default=False, help_text='When True, employees must verify face and be inside geofence to punch attendance'),
        ),
    ]
