# Generated by Django 5.1.10 on 2026-08-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_face_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='teamzen/organization/'),
        ),
    ]
