# Generated by Django 5.1.10 on 2026-08-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_imagefield_max_length_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='face_attendance_enabled',
            field=models.BooleanField(default=False, help_text='When True, employees must verify face to punch attendance (geofence remains soft-flagged)'),
        ),
    ]
