# Generated by Django 5.1.10 on 2026-08-13 17:11

import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_organization_weekend_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='weekend_days',
            field=models.JSONField(blank=True, default=organizations.models.default_weekend_days, help_text='Weekly off days as Python weekday ints (Mon=0 … Sun=6). Empty list means no weekly offs. Default is Sunday [6].'),
        ),
    ]
