# Generated by Django 5.1.10 on 2026-08-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_docs_vault_and_offboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cit_tds_office',
            field=models.TextField(blank=True, default='', help_text='CIT (TDS) office address shown on Form 16'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tan_number',
            field=models.CharField(blank=True, help_text='Tax Deduction Account Number (for Form 16)', max_length=20, null=True),
        ),
    ]
