# Generated by Django 5.1.10 on 2026-09-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_form16_tax_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='cit_tds_office',
            field=models.TextField(blank=True, default='', help_text='CIT (TDS) office address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tan_number',
            field=models.CharField(blank=True, help_text='Tax Deduction Account Number (TRACES / TDS)', max_length=20, null=True),
        ),
    ]
