# Generated by Django 5.1.10 on 2026-09-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_alter_organization_cit_tds_office_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officelocation',
            options={'ordering': ['id']},
        ),
    ]
