# Generated by Django 5.1.10 on 2026-09-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_alter_officelocation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['id']},
        ),
    ]
