# Generated by Django 5.1.10 on 2026-08-13 17:11

import cloudinary_storage.storage
import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0004_docs_vault_and_offboarding'),
        ('organizations', '0018_docs_vault_and_offboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('id_proof', 'ID proof'), ('pan', 'PAN'), ('aadhaar', 'Aadhaar'), ('bank_proof', 'Bank proof'), ('education', 'Education'), ('hr_request', 'HR request'), ('exit_clearance', 'Exit clearance'), ('other', 'Other')], default='hr_request', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_requests', to=settings.AUTH_USER_MODEL)),
                ('fulfilled_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfills_requests', to='onboarding.employeedocument')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssuedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('form_16', 'Form 16'), ('salary_certificate', 'Salary certificate'), ('experience', 'Experience letter'), ('relieving', 'Relieving letter'), ('fnf_statement', 'F&F statement'), ('policy_ack', 'Policy acknowledgement'), ('other', 'Other')], default='other', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('financial_year', models.CharField(blank=True, default='', help_text='e.g. 2025-26 for Form 16', max_length=16)),
                ('file', models.FileField(blank=True, max_length=1024, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=documents.models.issued_document_upload_to)),
                ('file_url', models.URLField(blank=True, default='', max_length=1024)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('visible_to_employee', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_documents', to='organizations.organization')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_issued_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
