
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
from urllib.parse import urlparse, urlunparse, parse_qsl, urlencode


def normalize_redis_url(
    url: str,
    db_index: int | None = None,
    ssl_cert_reqs: str | None = None,
) -> str:
    if not url:
        fallback = f"redis://localhost:6379/{db_index or 0}"
        return fallback

    parsed = urlparse(url)
    query = dict(parse_qsl(parsed.query, keep_blank_values=True))

    if parsed.scheme == "rediss" and "ssl_cert_reqs" not in query and ssl_cert_reqs:
        query["ssl_cert_reqs"] = ssl_cert_reqs

    path = parsed.path
    if db_index is not None:
        path = f"/{db_index}"

    return urlunparse(parsed._replace(path=path, query=urlencode(query)))

def get_redis_url_with_db(url: str, db_index: int) -> str:
    return normalize_redis_url(url, db_index=db_index, ssl_cert_reqs="required")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Always load backend/.env (not CWD-dependent)
load_dotenv(BASE_DIR / ".env", override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key-for-build-purposes')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = ['*']

# Proxy settings for Docker/Nginx
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

CLIENT_URL = os.getenv('CLIENT_URL', 'http://localhost:3000')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'cloudinary',
    'django.contrib.staticfiles',
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "drf_spectacular",

    "strawberry.django",

    "users",
    "organizations",
    "payroll",
    "attendance",
    "leaves.apps.LeavesConfig",
    "ai_engine.apps.AiEngineConfig",
    "bot_gateway.apps.BotGatewayConfig",
    "mcp_oauth.apps.McpOauthConfig",
    "integrations.apps.IntegrationsConfig",
    "graphql",
    "notifications",
    "channels",
    "django_celery_beat",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


AUTH_USER_MODEL = "users.CustomUser"
ROOT_URLCONF = 'config.urls'

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    os.getenv('CLIENT_URL', "http://localhost:3000"),
    "http://localhost:3001",
    "https://teamzen-client.vercel.app",
    "https://teamzen-admin.vercel.app"
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_CREDENTIALS = True

if DEBUG:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    
    # Lax allows cookies to be sent on top-level navigations and same-site requests
    # which is appropriate for localhost usage.
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    ACCESS_TOKEN_COOKIE_SAMESITE = "Lax" 
    REFRESH_TOKEN_COOKIE_SAMESITE = "Lax"
else:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # None is required for cross-site cookies (e.g., frontend on different domain than backend)
    # But requires Secure=True.
    SESSION_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SAMESITE = "None"
    ACCESS_TOKEN_COOKIE_SAMESITE = "None"
    REFRESH_TOKEN_COOKIE_SAMESITE = "None"



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Prefer Redis when available; in local DEBUG fall back to in-memory so a
# unreachable Redis Cloud host does not break websockets / chat / cache.
RAW_REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
REDIS_URL = normalize_redis_url(RAW_REDIS_URL, ssl_cert_reqs="required")
FORCE_REDIS = os.getenv('FORCE_REDIS', 'False') == 'True'
USE_INMEMORY_CHANNELS = (DEBUG and not FORCE_REDIS) or os.getenv('USE_INMEMORY_CHANNELS', 'False') == 'True'

if USE_INMEMORY_CHANNELS:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [REDIS_URL],
                "prefix": "teamzen_ws:",
            },
        },
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

if os.getenv("DATABASE_URL"):
    tmpPostgres = urlparse(os.getenv("DATABASE_URL"))
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': tmpPostgres.path.replace('/', ''),
            'USER': tmpPostgres.username,
            'PASSWORD': tmpPostgres.password,
            'HOST': tmpPostgres.hostname,
            'PORT': 5432,
            'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "payroll"),
            "USER": os.getenv("DB_USER", "postgres"),
            "PASSWORD": os.getenv("DB_PASSWORD", "postgres"),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": "payroll",
#         "USER": "postgres",
#         "PASSWORD": "123",
#         "HOST": "localhost",
#         "PORT": "5432",
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = []

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# Legacy settings for compatibility
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

# Static & Media Storage (Django 4.2+)
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "users.authentication.CookieJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Payroll System API",
    "DESCRIPTION": "Enterprise Payroll & Leave Management APIs",
    "VERSION": "1.0.0",
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),     
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),    

    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "AUTH_COOKIE": "access_token",
    "AUTH_COOKIE_REFRESH": "refresh_token",
    "AUTH_COOKIE_SECURE": not DEBUG,  # True in production
    "AUTH_COOKIE_HTTP_ONLY": True,
    "AUTH_COOKIE_SAMESITE": "None" if not DEBUG else "Lax",  # "None" for cross-origin in production
    "AUTH_COOKIE_PATH": "/",
}
CSRF_TRUSTED_ORIGINS = [
    os.getenv('CLIENT_URL', 'http://localhost:3000'),
    os.getenv('ADMIN_URL', 'http://localhost:3000'),
    'http://localhost:3001',
    # Add production URLs
    # 'https://your-frontend-domain.com',
]

SESSION_COOKIE_SAMESITE = 'None' if not DEBUG else 'Lax'
SESSION_COOKIE_SECURE = not DEBUG  # True in production
CSRF_COOKIE_SAMESITE = 'None' if not DEBUG else 'Lax'
CSRF_COOKIE_SECURE = not DEBUG

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
    'STATIC_TAG': 'static',
    'MEDIA_TAG': 'media',
    'RESOURCE_TYPE': 'auto',
    'PRESERVE_EXTENSIONS': True,
}

# Hosted Teamzen mark for transactional emails (override with EMAIL_LOGO_URL if needed)
_CLOUDINARY_CLOUD_NAME = CLOUDINARY_STORAGE.get('CLOUD_NAME') or ''
EMAIL_LOGO_URL = os.getenv(
    'EMAIL_LOGO_URL',
    (
        f"https://res.cloudinary.com/{_CLOUDINARY_CLOUD_NAME}/image/upload/"
        "c_fit,w_240,h_120,b_white,f_png,q_auto/branding/teamzen_email_logo.png"
        if _CLOUDINARY_CLOUD_NAME
        else ""
    ),
)
# Celery Configuration
# Use Redis as the primary message broker on DB 0 explicitly
CELERY_BROKER_URL = normalize_redis_url(
    os.getenv('CELERY_BROKER_URL', os.getenv('REDIS_URL')),
    ssl_cert_reqs="CERT_REQUIRED",
)
CELERY_RESULT_BACKEND = normalize_redis_url(
    os.getenv('CELERY_RESULT_BACKEND', os.getenv('REDIS_URL')),
    ssl_cert_reqs="CERT_REQUIRED",
)
CELERY_CACHE_BACKEND = 'django-cache'

# Eager mode for local development to avoid needing a separate celery worker process
CELERY_TASK_ALWAYS_EAGER = os.getenv('CELERY_TASK_ALWAYS_EAGER', str(DEBUG)) == 'True'
CELERY_TASK_EAGER_PROPAGATES = True

# Aggressive TCP keepalives to prevent Cloud Redis Labs from silently dropping idle connections
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,
    'socket_timeout': 5,
    'socket_connect_timeout': 5,
    'socket_keepalive': True,
    'retry_on_timeout': True,
}
CELERY_REDIS_RETRY_ON_TIMEOUT = True
CELERY_REDIS_SOCKET_KEEPALIVE = True

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'run-monthly-accruals': {
        'task': 'leaves.task.run_monthly_leave_accrual',
        'schedule': crontab(day_of_month='1', hour=0, minute=0),  # Run at midnight on the 1st of every month
    },
    'run-yearly-carry-forward': {
        'task': 'leaves.task.run_yearly_carry_forward',
        'schedule': crontab(day_of_month='1', month_of_year='1', hour=0, minute=0), # Run at midnight on Jan 1st
    },
    'cleanup-read-notifications': {
        'task': 'notifications.tasks.cleanup_read_notifications',
        'schedule': crontab(hour=0, minute=0), # Run every day at midnight
    },
    'square-off-incomplete-checkouts': {
        'task': 'attendance.tasks.square_off_incomplete_checkouts',
        'schedule': crontab(hour=0, minute=1),  # Run at 00:01 AM daily (Asia/Kolkata)
    },
    'ai-notify-expiring-leaves': {
        'task': 'notifications.ai_tasks.notify_expiring_leaves',
        'schedule': crontab(day_of_week='monday', month_of_year='12', hour=10, minute=0),
    },
    'ai-notify-missing-checkout': {
        'task': 'notifications.ai_tasks.notify_missing_checkout',
        'schedule': crontab(hour=9, minute=0),
    },
    'ai-alert-low-attendance': {
        'task': 'notifications.ai_tasks.alert_low_attendance',
        'schedule': crontab(day_of_week='monday', hour=10, minute=30),
    },
    'ai-notify-manager-team-absence': {
        'task': 'notifications.ai_tasks.notify_manager_team_absence',
        'schedule': crontab(day_of_week='sunday', hour=19, minute=0),
    },
    'ai-send-team-pulse-brief': {
        'task': 'notifications.ai_tasks.send_team_pulse_brief',
        'schedule': crontab(day_of_week='monday', hour=9, minute=15),
    },
    'ai-detect-burnout-signals': {
        'task': 'notifications.ai_tasks.detect_burnout_signals',
        'schedule': crontab(day_of_week='monday', hour=10, minute=45),
    },
    'scan-payroll-anomalies': {
        'task': 'payroll.tasks.scan_payroll_anomalies_task',
        'schedule': crontab(hour=1, minute=30),
    },
    'auto-run-payroll-for-due-orgs': {
        'task': 'payroll.tasks.auto_run_payroll_for_due_orgs',
        'schedule': crontab(hour=1, minute=0),  # Daily 01:00; respects org payroll_cycle_day
    },
}

# AI Configuration
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# Cache Configuration
if USE_INMEMORY_CHANNELS:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'teamzen-local',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }

# Email Configuration
# Render commonly blocks or times out outbound SMTP on shared instances,
# so default to the Brevo HTTP API backend instead of SMTP.
EMAIL_BACKEND = 'notifications.email_backends.BrevoHTTPBackend'
BREVO_API_KEY = os.getenv('BREVO_API_KEY')
# SMTP is kept only as fallback / legacy configuration.
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp-relay.brevo.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# Telegram Bot Gateway (Sequence 1 — Conversational HR)
# ---------------------------------------------------------------------------
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_WEBHOOK_SECRET = os.getenv("TELEGRAM_WEBHOOK_SECRET", "")
BOT_SESSION_TTL_HOURS = int(os.getenv("BOT_SESSION_TTL_HOURS", "8"))

# ---------------------------------------------------------------------------
# Slack Bot Gateway (Sequence 6)
# ---------------------------------------------------------------------------
SLACK_BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN", "")
SLACK_SIGNING_SECRET = os.getenv("SLACK_SIGNING_SECRET", "")

# ---------------------------------------------------------------------------
# WhatsApp Cloud API (Meta)
# ---------------------------------------------------------------------------
WHATSAPP_ACCESS_TOKEN = os.getenv("WHATSAPP_ACCESS_TOKEN", "")
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_VERIFY_TOKEN = os.getenv("WHATSAPP_VERIFY_TOKEN", "")
WHATSAPP_APP_SECRET = os.getenv("WHATSAPP_APP_SECRET", "")
WHATSAPP_API_VERSION = os.getenv("WHATSAPP_API_VERSION", "v21.0")

# ---------------------------------------------------------------------------
# Google Calendar (Sequence 6)
# ---------------------------------------------------------------------------
GOOGLE_CALENDAR_CLIENT_ID = os.getenv("GOOGLE_CALENDAR_CLIENT_ID", "")
GOOGLE_CALENDAR_CLIENT_SECRET = os.getenv("GOOGLE_CALENDAR_CLIENT_SECRET", "")
GOOGLE_CALENDAR_REDIRECT_URI = os.getenv(
    "GOOGLE_CALENDAR_REDIRECT_URI",
    "http://localhost:8000/api/integrations/google/calendar/callback/",
)
FRONTEND_URL = os.getenv("FRONTEND_URL", os.getenv("CLIENT_URL", "http://localhost:3000"))
 
