# Generated by Django 5.1.10 on 2026-07-28 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('slack', 'Slack')], max_length=20)),
                ('chat_id', models.CharField(max_length=100)),
                ('auth_state', models.CharField(choices=[('awaiting_identity', 'Awaiting identity'), ('awaiting_otp', 'Awaiting OTP'), ('verified', 'Verified')], default='awaiting_identity', max_length=32)),
                ('pending_identity', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'platform', 'is_verified'], name='bot_gateway_user_id_2a87b2_idx')],
                'unique_together': {('platform', 'chat_id')},
            },
        ),
    ]
