# Generated by Django 5.1.10 on 2026-02-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_companyholiday_id_alter_leavebalance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
