# Generated by Django 5.2.11 on 2026-02-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_alter_leaverequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='status',
            new_name='_status',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_column='status', default='pending', max_length=20),
        ),
    ]
