# Generated by Django 5.1.10 on 2026-03-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_remove_leaverequest_status_leaverequest__status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='half_day_period',
            field=models.CharField(choices=[('full_day', 'Full Day'), ('first_half', 'First Half'), ('second_half', 'Second Half')], default='full_day', max_length=20),
        ),
    ]
