# Generated by Django 5.1.10 on 2026-07-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_leaveauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='google_event_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
