# Generated by Django 5.1.10 on 2026-07-29 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payroll_advances_and_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeComponentOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_excluded', models.BooleanField(default=False, help_text='If True, this component is skipped for this employee')),
                ('override_value', models.DecimalField(blank=True, decimal_places=2, help_text='Custom flat amount. If null, uses the structure default.', max_digits=12, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarycomponent')),
                ('employee_salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_overrides', to='payroll.employeesalarystructure')),
            ],
            options={
                'unique_together': {('employee_salary', 'component')},
            },
        ),
    ]
