# Generated by Django 5.1.10 on 2026-08-13 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_docs_vault_and_offboarding'),
        ('onboarding', '0004_docs_vault_and_offboarding'),
        ('organizations', '0018_docs_vault_and_offboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffboardingTaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assignee_role', models.CharField(choices=[('hr', 'HR'), ('it', 'IT'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('phase', models.CharField(choices=[('notice', 'Notice period'), ('last_day', 'Last day'), ('clearance', 'Clearance'), ('settlement', 'Settlement'), ('letters', 'Letters')], default='clearance', max_length=20)),
                ('due_offset_days', models.IntegerField(default=0, help_text='Days relative to last working day (negative = before)')),
                ('requires_document_category', models.CharField(blank=True, choices=[('id_proof', 'ID proof'), ('exit_clearance', 'Exit clearance'), ('hr_request', 'HR request'), ('other', 'Other')], default='', max_length=32)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOffboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In progress'), ('settlement_pending', 'Settlement pending'), ('letters_pending', 'Letters pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='initiated', max_length=32)),
                ('reason', models.CharField(choices=[('resign', 'Resignation'), ('terminate', 'Termination'), ('contract_end', 'Contract end'), ('other', 'Other')], default='resign', max_length=32)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_offboardings', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_offboardings', to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExitInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exit_invites', to=settings.AUTH_USER_MODEL)),
                ('offboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='offboarding.employeeoffboarding')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FnfSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('hr_approved', 'HR approved'), ('acknowledged', 'Acknowledged by employee'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('pro_rata_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('leave_encashment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bonus_gratuity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_additions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('recoveries', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('statement_pdf_url', models.URLField(blank=True, default='', max_length=1024)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fnf_settlements', to=settings.AUTH_USER_MODEL)),
                ('offboarding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='offboarding.employeeoffboarding')),
            ],
        ),
        migrations.CreateModel(
            name='OffboardingTaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assignee_role', models.CharField(default='employee', max_length=20)),
                ('phase', models.CharField(default='clearance', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('requires_document_category', models.CharField(blank=True, default='', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_offboarding_tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_offboarding_tasks', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='offboarding.offboardingtaskdefinition')),
                ('offboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='offboarding.employeeoffboarding')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OffboardingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offboarding_templates', to=settings.AUTH_USER_MODEL)),
                ('it_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_templates_as_it', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_templates', to='organizations.organization')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='offboardingtaskdefinition',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_definitions', to='offboarding.offboardingtemplate'),
        ),
        migrations.AddField(
            model_name='employeeoffboarding',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboardings', to='offboarding.offboardingtemplate'),
        ),
        migrations.CreateModel(
            name='ExitLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type', models.CharField(choices=[('experience', 'Experience letter'), ('relieving', 'Relieving letter'), ('salary_certificate', 'Salary certificate')], max_length=32)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body_html', models.TextField(blank=True, default='')),
                ('pdf_url', models.URLField(blank=True, default='', max_length=1024)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued')], default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exit_letters', to=settings.AUTH_USER_MODEL)),
                ('issued_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_letters', to='documents.issueddocument')),
                ('letter_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_letters', to='onboarding.documentlettertemplate')),
                ('offboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='offboarding.employeeoffboarding')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('offboarding', 'letter_type')},
            },
        ),
    ]
