# Generated by Django 5.1.10 on 2026-08-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_offerletter_signed_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='source',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('hr_request', 'HR request'), ('offboarding', 'Offboarding'), ('self', 'Self upload')], default='onboarding', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentlettertemplate',
            name='letter_type',
            field=models.CharField(choices=[('offer', 'Offer letter'), ('experience', 'Experience letter'), ('relieving', 'Relieving letter'), ('salary_certificate', 'Salary certificate')], default='offer', max_length=32),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='category',
            field=models.CharField(choices=[('id_proof', 'ID proof'), ('pan', 'PAN'), ('aadhaar', 'Aadhaar'), ('bank_proof', 'Bank proof'), ('education', 'Education'), ('offer', 'Offer letter'), ('signed_policy', 'Signed policy'), ('form_16', 'Form 16'), ('hr_request', 'HR request'), ('exit_clearance', 'Exit clearance'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='onboardingtaskdefinition',
            name='requires_document_category',
            field=models.CharField(blank=True, choices=[('id_proof', 'ID proof'), ('pan', 'PAN'), ('aadhaar', 'Aadhaar'), ('bank_proof', 'Bank proof'), ('education', 'Education'), ('offer', 'Offer letter'), ('signed_policy', 'Signed policy'), ('form_16', 'Form 16'), ('hr_request', 'HR request'), ('exit_clearance', 'Exit clearance'), ('other', 'Other')], default='', max_length=32),
        ),
    ]
