def get_base_template(
    title: str,
    body_content: str,
    accent_color: str = "#4F46E5",
    accent_light: str = "#EEF2FF",
    logo_url: str = "",
    footer_text: str = "Teamzen HRMS",
    company_url: str = "#",
) -> str:
    """Generate the base responsive HTML email template."""
    return f"""<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap');
            body {{ background: #F8FAFC; font-family: 'Inter', sans-serif; margin: 0; padding: 32px 8px; }}
            .container {{ max-width: 500px; margin: 40px auto; background: white; border: 1px solid #E2E8F0; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
            .content {{ padding: 0; }}
            .footer {{ padding: 24px 40px; background: #F8FAFC; text-align: center; border-top: 1px solid #E2E8F0; }}
            p {{ font-size: 15px; color: #475569; line-height: 1.7; margin: 0 0 16px 0; }}
            h1 {{ color: #0F172A !important; }}
            .btn {{ display: inline-block; padding: 12px 24px; color: white; border-radius: 6px; text-decoration: none; font-weight: 600; text-align: center; }}
        </style>
    </head>
    <body>
        <div class="container">
            <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%">
            {body_content}
            </table>
            <div class="footer">
                <p style="color: #64748B; font-size: 12px; margin: 0;">This notification was generated by {footer_text}.</p>
            </div>
        </div>
    </body>
</html>
"""

def button_html(text: str, url: str, bg_color: str = "#4F46E5", text_color: str = "#ffffff") -> str:
    return f'<a href="{url}" style="background-color: {bg_color}; color: {text_color}; text-decoration: none; padding: 12px 24px; border-radius: 6px; font-weight: 600; display: inline-block; text-align: center;">{text}</a>'

def info_row_html(label: str, value: str, icon: str = "", accent_color: str = "#4F46E5") -> str:
    icon_str = f"{icon} " if icon else ""
    return f"""
    <tr>
        <td style="padding: 6px 0;">
            <p style="margin: 0; font-size: 14px; color: #475569;">
                <strong style="color: {accent_color};">{icon_str}{label}:</strong> {value}
            </p>
        </td>
    </tr>
    """

def status_badge_html(text: str, text_color: str, bg_color: str) -> str:
    return f'<span style="background-color: {bg_color}; color: {text_color}; padding: 4px 12px; border-radius: 99px; font-size: 11px; font-weight: bold; text-transform: uppercase;">{text}</span>'
