# Generated by Django 5.1.10 on 2026-02-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('personal', 'Personal'), ('admin', 'Admin')], default='personal', max_length=20),
        ),
    ]
