# Generated by Django 5.1.10 on 2026-01-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='login_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='logout_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
