# Generated by Django 5.1.10 on 2026-01-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_login_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='login_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='logout_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late_login', 'Late Login'), ('early_logout', 'Early Logout'), ('half_day', 'Half Day'), ('leave', 'Leave'), ('holiday', 'Holiday')], default='absent', max_length=20),
        ),
    ]
