# Generated by Django 5.1.10 on 2026-01-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancerecord_login_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecorrection',
            name='corrected_login_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancecorrection',
            name='corrected_logout_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
