# Generated by Django 5.1.10 on 2026-02-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancecorrection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='actual_login_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='actual_logout_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
