# Generated by Django 5.1.10 on 2026-02-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendancecorrection_id_and_more'),
        ('attendance', '0006_attendancerecord_actual_login_time_and_more'),
    ]

    operations = [
    ]
