# Generated by Django 5.1.10 on 2026-08-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_remove_attendancecorrection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='teamzen/attendance_selfies/'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='teamzen/attendance_selfies/'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='face_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='face_verified',
            field=models.BooleanField(default=False),
        ),
    ]
