# Generated by Django 5.1.10 on 2026-09-25 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_imagefield_max_length_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='effective_worked_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='out_of_fence_heartbeats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='roaming_anomaly_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='roaming_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='total_heartbeats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='valid_heartbeats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AttendanceHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('distance_meters', models.IntegerField(help_text='Calculated distance in meters from assigned office')),
                ('is_within_geofence', models.BooleanField(default=False)),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('is_mocked', models.BooleanField(default=False, help_text='Detected fake GPS / mock provider')),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='attendance.attendancerecord')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['attendance_record', 'timestamp'], name='attendance__attenda_ff1158_idx')],
            },
        ),
    ]
