# Generated by Django 5.1.10 on 2026-09-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendancerecord_effective_worked_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='out_of_fence_heartbeats',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='total_heartbeats',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='valid_heartbeats',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
