# Generated by Django 5.1.10 on 2026-09-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_attendancerecord_approval_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='approval_remarks',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='roaming_notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
